### ISSUE TITLE
Update README for New Comers

### ISSUE THREAD

**Issue by channprj** [channprj/google-search-navigator#1]
## Summary

- Add install button
- Add screenshots or simple gifs
- Add "How to use" sections

**Comment by rach-m** [comment]
I can do this!

**Comment by sebanti10** [comment]
I would like to contribute!

**Comment by phg9898** [comment]
Hi!
For Hacktoberfest, I would like to add badges to your README file. 
like 
[![GitHub stars](https://img.shields.io/github/stars/channprj/google-search-navigator)](https://github.com/channprj/google-search-navigator/stargazers)
[![GitHub forks](https://img.shields.io/github/forks/channprj/google-search-navigator)](https://github.com/channprj/google-search-navigator/network)
[![GitHub issues](https://img.shields.io/github/issues/channprj/google-search-navigator)](https://github.com/channprj/google-search-navigator/issues)
How about that?

**Comment by channprj** [comment]
@phg9898 That's ok. Feel free to make pr. ☺️
